/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package recipemanager;

import java.awt.FlowLayout;
import javax.swing.DefaultListModel;

public class RecipePanel extends javax.swing.JPanel {

    /**
     * Creates new form RecipePanel
     */
    public RecipePanel() {
        initComponents();
        
        updateIngredients();
        
        IngredientListPanel.setLayout(new FlowLayout());
    }
    
        //get the data from the main class, and update panel
    public void updateIngredients(){
        DefaultListModel model = (DefaultListModel) recipePanel.getModel();
        
        //remove anything that might be already there
        model.removeAllElements();
        
        //go through every ingredient and add it to the list (model)
        for(int i = 0; i < RecipeManager.allRecipes.size(); i++){
            Recipe rec = RecipeManager.allRecipes.get(i); //get the i-th ingredient

            model.addElement(rec); //add it to the list
        }    
    }
    
    
    //this will be called from the ingredients panel (outside of this panel)
    public void updateAddFields(Ingredient ing){
        if(ing != null){
            selectedIngredientToAdd.setText(ing.toString());
            addIngredientButton.setEnabled(true);
        }
        else{
            selectedIngredientToAdd.setText("No Ingredient Selected");
            addIngredientButton.setEnabled(false);
        }
        
        
    }
    
    public Recipe getSelectedRecipe(){
        return (Recipe) recipePanel.getSelectedValue();
    }
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        recipePanel = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        IngredientListPanel = new javax.swing.JPanel();
        recipeBankHeader = new javax.swing.JLabel();
        addRecipeButton = new javax.swing.JButton();
        deleteRecipeButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        ingredientToAddLabel = new javax.swing.JLabel();
        selectedIngredientToAdd = new javax.swing.JLabel();
        quantityToAddLabel = new javax.swing.JLabel();
        ingredientQuantityTextField = new javax.swing.JTextField();
        addIngredientButton = new javax.swing.JButton();
        addNewRecipeTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        recipePanel.setFont(new java.awt.Font("AdornS Condensed Sans", 0, 24)); // NOI18N
        recipePanel.setModel(new DefaultListModel());
        recipePanel.setSelectionBackground(new java.awt.Color(0, 153, 153));
        recipePanel.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                recipePanelValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(recipePanel);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        IngredientListPanel.setBorder(null);
        IngredientListPanel.setMaximumSize(new java.awt.Dimension(500, 32767));
        IngredientListPanel.setNextFocusableComponent(addRecipeButton);
        IngredientListPanel.setPreferredSize(new java.awt.Dimension(200, 300));

        javax.swing.GroupLayout IngredientListPanelLayout = new javax.swing.GroupLayout(IngredientListPanel);
        IngredientListPanel.setLayout(IngredientListPanelLayout);
        IngredientListPanelLayout.setHorizontalGroup(
            IngredientListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 414, Short.MAX_VALUE)
        );
        IngredientListPanelLayout.setVerticalGroup(
            IngredientListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(IngredientListPanel);

        recipeBankHeader.setFont(new java.awt.Font("Bungee", 1, 48)); // NOI18N
        recipeBankHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        recipeBankHeader.setText("Recipe Bank");

        addRecipeButton.setText("Add New Recipe");
        addRecipeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRecipeButtonActionPerformed(evt);
            }
        });

        deleteRecipeButton.setText("Delete Recipe");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ingredientToAddLabel.setFont(new java.awt.Font("Bungee", 0, 18)); // NOI18N
        ingredientToAddLabel.setText("Ingredient to add:");

        selectedIngredientToAdd.setFont(new java.awt.Font("AdornS Condensed Sans", 0, 18)); // NOI18N
        selectedIngredientToAdd.setText("No Ingredient Selected");

        quantityToAddLabel.setFont(new java.awt.Font("Bungee", 0, 18)); // NOI18N
        quantityToAddLabel.setText("Quantity to add:");

        ingredientQuantityTextField.setFont(new java.awt.Font("AdornS Condensed Sans", 0, 18)); // NOI18N

        addIngredientButton.setText("Add Ingredient");
        addIngredientButton.setToolTipText("Add ingredient to recipe");
        addIngredientButton.setEnabled(false);
        addIngredientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addIngredientButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addIngredientButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(selectedIngredientToAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ingredientQuantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ingredientToAddLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(quantityToAddLabel)))))
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingredientToAddLabel)
                    .addComponent(quantityToAddLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectedIngredientToAdd)
                    .addComponent(ingredientQuantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addIngredientButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        addNewRecipeTextField.setSelectionColor(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Bungee", 0, 14)); // NOI18N
        jLabel1.setText("New Recipe:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(recipeBankHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(182, 182, 182))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(deleteRecipeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(addRecipeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(addNewRecipeTextField))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(51, 51, 51)
                                    .addComponent(jLabel1))))
                        .addGap(35, 35, 35)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(11, 11, 11))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(recipeBankHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addNewRecipeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addRecipeButton)
                        .addGap(18, 18, 18)
                        .addComponent(deleteRecipeButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(29, 29, 29))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void recipePanelValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_recipePanelValueChanged
        Recipe rec = (Recipe) recipePanel.getSelectedValue();
        //first clear the container panel
        IngredientListPanel.removeAll();
        
        if(rec != null){//add a panel for each ingredient of the recipe
           
            
            int n = rec.getNumberOfIngredients();
            for(int i = 0; i < n; i++){
                SingleIngredient si = new SingleIngredient(); //create a panel for the i-th ingredient
                
                Ingredient ing = rec.getIngredient(i);
                si.setIngredient(ing);
                
                double q = rec.getQuantity(i);
                si.setQuantity(q);
                
                //add the panel to the list of panels
                IngredientListPanel.add(si);
                
            }
        }            
        
        IngredientListPanel.revalidate(); //use this when a change is not immediately visible
                                //it forces Swing to re-layout and redraw
        
        IngredientListPanel.repaint();
        
    }//GEN-LAST:event_recipePanelValueChanged

    
    //add ingredient to recipe
    private void addIngredientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addIngredientButtonActionPerformed

        
        
    }//GEN-LAST:event_addIngredientButtonActionPerformed

    //add new recipe
    private void addRecipeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRecipeButtonActionPerformed
        Recipe rec = new Recipe();
        String name; 
        
        
        //create a new recipe object
        
        Recipe recipe = new Recipe();
        
        name = addNewRecipeTextField.getText();
        
        //populate the fields of the recipe
        recipe.setName(name);
 
        //add it to the repository in Recipe Manager class
        RecipeManager.allRecipes.add(recipe);
        
        
        //update the interface
        updateIngredients();
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_addRecipeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel IngredientListPanel;
    private javax.swing.JButton addIngredientButton;
    private javax.swing.JTextField addNewRecipeTextField;
    private javax.swing.JButton addRecipeButton;
    private javax.swing.JButton deleteRecipeButton;
    private javax.swing.JTextField ingredientQuantityTextField;
    private javax.swing.JLabel ingredientToAddLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel quantityToAddLabel;
    private javax.swing.JLabel recipeBankHeader;
    private javax.swing.JList recipePanel;
    private javax.swing.JLabel selectedIngredientToAdd;
    // End of variables declaration//GEN-END:variables
}
